### PR TITLE
Create centos_installation.md

### PR DESCRIPTION
**Pull request by pkleanthous-zz**
Add documentation how to install Slat-Master and napalm on CentOS 7.

### CODE REVIEW

**Comment by mirceaulinic** [comment]
Thanks @pkleanthous - that's a nice addition! Could you please insert a link in the main README to point to this document? Thanks!

**Comment by pkleanthous-zz** [comment]
Hi @mirceaulinic is it better to edit the main README and add the relevant sections for CentOS ?

**Comment by mirceaulinic** [comment]
The main README is already pretty long. I think a separate document would be more suitable; and you proposal is already like that. Could you just insert a link in the README pointing to this new doc? Thanks!

**Comment by pkleanthous-zz** [comment]
@mirceaulinic Done.

**Comment by mirceaulinic** [comment]
Efcharisto! :)

**Pull request merged**
